Repository Dongguk-ICE-HANIUM/Medi_Guard_Server, pull requests merged in 2025-08, with the labels that each got.

#14 ✨ [Feat] - Patient User 엔티티 설계를 한다
  src/main/java/hanium/dongguk/user/core/domain/EStatus.java
  src/main/java/hanium/dongguk/user/core/domain/User.java
  src/main/java/hanium/dongguk/user/patient/UserPatient.java
Labels: :sparkles: feature

#22 🐛 [Fix] - My page 엔티티 설계를 한다 - 보완
  src/main/java/hanium/dongguk/calendar/domain/Calendar.java
  src/main/java/hanium/dongguk/calendar/domain/CalendarDrug.java
  src/main/java/hanium/dongguk/calendar/domain/EEmotion.java
  src/main/java/hanium/dongguk/question/domain/EQuestionType.java
  src/main/java/hanium/dongguk/question/domain/Question.java
Labels: :bug:bug

#18 ✨ [Feat] - Spring Actuator를 적용한다.
  Dockerfile
  application-dev.yml
  application.yml
  build.gradle
  medi-guard/Chart.yaml
  medi-guard/templates/NOTES.txt
  medi-guard/templates/_helpers.tpl
  medi-guard/templates/deployment.yaml
  medi-guard/templates/hpa.yaml
  medi-guard/templates/ingress.yaml
  medi-guard/templates/service.yaml
  medi-guard/templates/serviceaccount.yaml
  medi-guard/templates/tests/test-connection.yaml
  medi-guard/value/base.yaml
  medi-guard/value/local.yaml
  medi-guard/value/prod.yaml
  src/main/java/hanium/dongguk/global/constants/Constants.java
  src/main/java/hanium/dongguk/global/health/HealthController.java
  src/main/java/hanium/dongguk/global/security/config/PortRequestMatcher.java
  src/main/java/hanium/dongguk/global/security/config/SecurityConfig.java
Labels: :sparkles: feature

#35 🌐 [CI] - dev 브랜치가 push되었을 때, CI가 작동한다.(3)
  .github/workflows/dev-deploy.yml
Labels: :hammer: !HOTFIX

#36 🌐 [CI] - dev 브랜치가 push되었을 때, CI가 작동한다.(3)
  .github/workflows/dev-deploy.yml
Labels: :hammer: !HOTFIX

#27 ✨ [Feat] question api 개발
  src/main/java/hanium/dongguk/calendar/domain/Calendar.java
  src/main/java/hanium/dongguk/calendar/domain/CalendarDrug.java
  src/main/java/hanium/dongguk/calendar/domain/CalendarRepository.java
  src/main/java/hanium/dongguk/calendar/exception/CalendarErrorCode.java
  src/main/java/hanium/dongguk/calendar/service/CalendarRetriever.java
  src/main/java/hanium/dongguk/calendar/service/CalendarSaver.java
  src/main/java/hanium/dongguk/global/annotation/UserId.java
  src/main/java/hanium/dongguk/global/security/config/SecurityConfig.java
  src/main/java/hanium/dongguk/global/security/info/AuthenticationResponse.java
  src/main/java/hanium/dongguk/patientdrug/domain/PatientDrug.java
  src/main/java/hanium/dongguk/patientdrug/domain/PatientDrugRepository.java
  src/main/java/hanium/dongguk/question/controller/QuestionApiSwagger.java
  src/main/java/hanium/dongguk/question/controller/QuestionController.java
  src/main/java/hanium/dongguk/question/domain/Question.java
  src/main/java/hanium/dongguk/question/domain/QuestionRepository.java
  src/main/java/hanium/dongguk/question/dto/request/SaveQuestionDto.java
  src/main/java/hanium/dongguk/question/dto/request/SaveQuestionListRequestDto.java
  src/main/java/hanium/dongguk/question/dto/request/UpdateQuestionDto.java
  src/main/java/hanium/dongguk/question/dto/request/UpdateQuestionListRequestDto.java
  src/main/java/hanium/dongguk/question/dto/response/QuestionDto.java
  src/main/java/hanium/dongguk/question/dto/response/QuestionResponseDto.java
  src/main/java/hanium/dongguk/question/exception/QuestionErrorCode.java
  src/main/java/hanium/dongguk/question/service/QuestionRetriever.java
  src/main/java/hanium/dongguk/question/service/QuestionSaver.java
  src/main/java/hanium/dongguk/question/service/QuestionService.java
  src/main/java/hanium/dongguk/question/service/QuestionValidator.java
  src/main/java/hanium/dongguk/sideeffect/domain/SideEffect.java
Labels: :sparkles: feature
